{
 "title": "Dotnet Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(systemruntime_threadpool_queue_length{}, cluster)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(systemruntime_threadpool_queue_length{}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Lookups Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "systemnetnameresolution_dns_lookups_requested{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Current DNS Lookups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "systemnetnameresolution_current_dns_lookups{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "DNS Lookups Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "systemnetnameresolution_dns_lookups_duration_ms{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Kestrel (Requests/Connections/TLS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_requests_per_second{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Connections Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_connections_per_second{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "TLS Handshakes Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_tls_handshakes_per_second{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_current_requests{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_current_connections{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Current TLS Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_current_tls_handshakes{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_total_requests{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 35 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_total_connections{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Total TLS Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_total_tls_handshakes{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Request Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_request_queue_length{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Connection Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_connection_queue_length{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_failed_requests{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Failed TLS Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "microsoftaspnetcoreserverkestrel_failed_tls_handshakes{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "TLS 2 Handshake Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "systemnetsecurity_tls12_handshake_duration_ms{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "TLS 3 Handshake Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "systemnetsecurity_tls13_handshake_duration_ms{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Outgoing Connections Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "systemnetsockets_outgoing_connections_established{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Incoming Connections Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "systemnetsockets_incoming_connections_established{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Exception Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "systemruntime_exception_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Gen 0 Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{kubernetes_pod_name=~\"$Pod\"}/1000000",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Gen 0 GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "systemruntime_gen_0_gc_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Gen 1 Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "systemruntime_gen_1_size_bytes{kubernetes_pod_name=~\"$Pod\"}/1000000",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Gen 1 GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "systemruntime_gen_1_gc_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Gen 2 Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "systemruntime_gen_2_size_bytes{kubernetes_pod_name=~\"$Pod\"}/1000000",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Gen 2 GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "systemruntime_gen_2_gc_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Large Object Heap (LOH) Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "systemruntime_loh_size_bytes{kubernetes_pod_name=~\"$Pod\"}/1000000",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Time in GC since last GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Allocation Rate (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{kubernetes_pod_name=~\"$Pod\"}/1000000",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "GC Heap Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "systemruntime_gc_heap_size_bytes{kubernetes_pod_name=~\"$Pod\"}/1000000",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Threadpool Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_thread_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Threadpool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_queue_length{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Threadpool Completed Items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_completed_items_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  },
  {
   "title": "Monitor Lock Contention Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "systemruntime_monitor_lock_contention_count{kubernetes_pod_name=~\"$Pod\"}",
     "groupByUnit": "m",
     "groupByValue": "1",
     "healthHistoryValueTransform": "raw",
     "healthQueryType": "Topology",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metricsQueryType": "ui",
     "missingDataBehavior": "keepMissingData",
     "monitorUiType": "modal",
     "orderAggFunc": "avg",
     "orderBy": "desc",
     "service": "metrics",
     "showTop": "40"
    }
   ]
  }
 ]
}